### PR TITLE
Foxtrot Sprint 1

### PR DESCRIPTION
**Pull request by nimrossum**
# Changes

- Migrate to .NET 3.1
    - Minor refactoring in codebase to comply with .NET changes
    - Updated packages
    - Update tests to run on .NET 3.1

### CODE REVIEW

**Review by frederikfink — APPROVED** [review]
Looks good :D

**Review by WizOfRob — APPROVED** [review]
OK!

**Review by WizOfRob — COMMENTED** [review]
Line 3 in .travis.yml creates an error. "dotnet: 3.1.0" as it couldn't be found. Perhaps change to 3.1.13, as that's the most recent LTS patch. Also probably shouldn't be merged into the master branch, but rather the Develop branch?

**Comment by WizOfRob** [comment]
Check fail, also wrong branch.

**Pull request closed without merging**
